In [2]:
import pandas as pd
import numpy as np

eight = pd.read_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/SMOTED_80.parquet')
two = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/MOUNTAIN_20.parquet')

In [3]:
eight_land = eight[['is_landslided']]
# two_land = two[['is_landslided']]

eight_land.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/SMOTE_LANDSLIDE_80.parquet', index=False)
# two_land.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/LANDSLIDE_20.parquet', index=False)
eight_land

        is_landslided
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0
...               ...
912327            1.0
912328            1.0
912329            1.0
912330            1.0
912331            1.0

[912332 rows x 1 columns]

In [58]:
code = pd.read_csv('../HEATMAP/HEATMAP_CODE.csv')
print(code.columns.tolist())

['CMBLC_ID', 'SBLT_ID', 'SMAR_NO', 'SLTP_CD', 'STQLT_CD', 'MPDMR_NO', 'RHGLT_GGRP', 'WTHR_CD', 'TPGRP_TPCD', 'CLZN_CD', 'PRRCK_LARG', 'SOIL_DRNGE', 'ALTTD_CD', 'ACCMA_FOR', 'WASH_CD', 'SLANT_TYP', 'EIGHT_CD', 'ROCK_EXDGR', 'WIND_EXDGR', 'WTEFF_DGR', 'SIAFLR_STP', 'SIBFLR_STP', 'SIAFLR_SLD', 'SIBFLR_SLD', 'SIAFLR_ERC', 'SIBFLR_ERC', 'SIAFLR_ORM', 'SIBFLR_ORM', 'SIAFLR_SCS', 'SIBFLR_SCS', 'SIAFLR_CBS', 'SIBFLR_CBS', 'SIAFLR_STR', 'SIBFLR_STR', 'SIAFLR_HGD', 'SIBFLR_HGD', 'SIAFLR_CNS', 'SIBFLR_CNS', 'SIAFLR_HYP', 'SIAFLR_HER', 'SIBFLR_HER', 'SIAFLR_SMA', 'SIBFLR_SMA', 'SIAFLR_MDD', 'SIBFLR_MDD', 'SIAFLR_LAR', 'SIBFLR_LAR', 'KOFTR_CD']

In [10]:
eight_cols = eight.columns.tolist()
two_cols = two.columns.tolist()

print(eight_cols)

['avg_temp', 'lowest_temp', 'highest_temp', 'rainfalling_hr_asos', '1hr_rainfall_mm_asos', 'daily_rainfall_asos', 'max_windspeed_asos', 'avg_windspeed_asos', 'avg_dewpoint_temp', 'min_rhum_per', 'avg_rhum_per', 'avg_vapor_hpa', 'avg_local_press_hpa', 'max_sea_press_hpa', 'min_sea_press_hpa', 'avg_sea_press_hpa', 'avg_cloud', 'CMBLC_ID', 'SBLT_ID', 'SMAR_NO', 'SLTP_CD', 'STQLT_CD', 'RHGLT_GGRP', 'WTHR_CD', 'TPGRP_TPCD', 'CLZN_CD', 'PRRCK_LARG', 'SOIL_DRNGE', 'LOCTN_GRDN', 'ALTTD_CD', 'ACCMA_FOR', 'WASH_CD', 'SLANT_TYP', 'EIGHT_CD', 'ROCK_EXDGR', 'RIDGE_VS', 'WIND_EXDGR', 'WTEFF_DGR', 'VLDTY_SLDP', 'SIAFLR_STP', 'SIBFLR_STP', 'SIAFLR_SLD', 'SIBFLR_SLD', 'SIAFLR_ERC', 'SIBFLR_ERC', 'SIAFLR_ORM', 'SIBFLR_ORM', 'SIAFLR_SCS', 'SIBFLR_SCS', 'SIAFLR_CBS', 'SIBFLR_CBS', 'SIAFLR_STR', 'SIBFLR_STR', 'SIAFLR_HGD', 'SIBFLR_HGD', 'SIAFLR_CNS', 'SIBFLR_CNS', 'SIAFLR_HYP', 'SIAFLR_HER', 'SIBFLR_HER', 'SIAFLR_SMA', 'SIBFLR_SMA', 'SIAFLR_MDD', 'SIBFLR_MDD', 'SIAFLR_LAR', 'SIBFLR_LAR', 'KOFTR_CD', 'TREEHT1', 'TREEHT2', 'TREEHT3', 'TREEHT4', 'TREEHT5', 'FRAG1', 'FRAG2', 'FRAG3', 'FRAG4', 'FRAG5', 'REAL_STIND', 'INTGR_TYP', 'STQGD_VAL', 'TRHGH_SUM', 'TRHGH_AVRG', 'TOT_FRAG', 'AVRG_FRAG', 'LARCH_STIN', 'KRPN_STIND', 'GNGN_LCLT', 'CNDST_PINE', 'ACTSM_STIN', 'JBLPN_STIN', 'is_landslided']

In [4]:
eight_reals = eight[['avg_temp', 'lowest_temp', 'highest_temp', 'rainfalling_hr_asos', '1hr_rainfall_mm_asos', 'daily_rainfall_asos', 'max_windspeed_asos', 'avg_windspeed_asos', 'avg_dewpoint_temp', 'min_rhum_per', 'avg_rhum_per', 'avg_vapor_hpa', 'avg_local_press_hpa', 'max_sea_press_hpa', 'min_sea_press_hpa', 'avg_sea_press_hpa', 'avg_cloud', 'LOCTN_GRDN', 'RIDGE_VS', 'VLDTY_SLDP', 'TREEHT1', 'TREEHT2', 'TREEHT3', 'TREEHT4', 'TREEHT5', 'FRAG1', 'FRAG2', 'FRAG3', 'FRAG4', 'FRAG5', 'REAL_STIND', 'INTGR_TYP', 'STQGD_VAL', 'TRHGH_SUM', 'TRHGH_AVRG', 'TOT_FRAG', 'AVRG_FRAG', 'LARCH_STIN', 'KRPN_STIND', 'GNGN_LCLT', 'CNDST_PINE', 'ACTSM_STIN', 'JBLPN_STIN']]
eight_reals #실수만 뽑기

,avg_temp,lowest_temp,highest_temp,rainfalling_hr_asos,1hr_rainfall_mm_asos,daily_rainfall_asos,max_windspeed_asos,avg_windspeed_asos,avg_dewpoint_temp,min_rhum_per,...,TRHGH_SUM,TRHGH_AVRG,TOT_FRAG,AVRG_FRAG,LARCH_STIN,KRPN_STIND,GNGN_LCLT,CNDST_PINE,ACTSM_STIN,JBLPN_STIN
0,14.7,12.4,17.6,0.0,0.0,0.0,3.5,1.7,12.8,78.0,...,84.000000,16.799999,233.0,17.0,14.0,14.0,12.0,0.0,17.0,11.0
1,14.7,12.4,17.6,0.0,0.0,0.0,3.5,1.7,12.8,78.0,...,76.500000,15.300000,191.0,15.0,13.0,14.0,9.0,9.0,16.0,11.0
2,14.7,12.4,17.6,0.0,0.0,0.0,3.5,1.7,12.8,78.0,...,70.300003,14.000000,199.0,14.0,12.0,12.0,7.0,7.0,14.0,9.0
3,14.7,12.4,17.6,0.0,0.0,0.0,3.5,1.7,12.8,78.0,...,85.699997,17.100000,241.0,17.0,13.0,15.0,10.0,9.0,17.0,12.0
4,14.7,12.4,17.6,0.0,0.0,0.0,3.5,1.7,12.8,78.0,...,0.000000,0.000000,0.0,0.0,13.0,14.0,10.0,10.0,17.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912327,26.3,21.8,33.0,0.0,0.5,0.5,4.3,0.9,22.4,48.0,...,75.300003,15.000000,139.0,15.0,12.0,12.0,7.0,7.0,14.0,10.0
912328,22.8,21.2,24.1,0.0,13.1,24.3,1.6,0.3,22.2,93.0,...,0.000000,0.000000,0.0,0.0,15.0,15.0,12.0,12.0,19.0,12.0
912329,23.0,20.0,26.8,0.0,0.5,0.9,1.9,0.4,22.5,86.0,...,63.200001,12.600000,164.0,13.0,13.0,13.0,0.0,8.0,12.0,0.0
912330,21.8,19.8,24.0,0.0,31.2,170.1,2.7,0.9,21.3,91.0,...,78.800003,15.700000,166.0,16.0,14.0,13.0,11.0,8.0,14.0,10.0
912331,23.4,22.5,24.2,0.0,8.5,43.4,2.3,0.7,23.1,94.0,...,69.699997,13.900000,172.0,14.0,15.0,14.0,10.0,10.0,18.0,13.0

In [5]:
eight_codes = eight[['CMBLC_ID', 'SBLT_ID', 'SMAR_NO', 'SLTP_CD', 'STQLT_CD', 'RHGLT_GGRP', 'WTHR_CD', 'TPGRP_TPCD', 'CLZN_CD', 'PRRCK_LARG', 'SOIL_DRNGE', 'ALTTD_CD', 'ACCMA_FOR', 'WASH_CD', 'SLANT_TYP', 'EIGHT_CD', 'ROCK_EXDGR', 'WIND_EXDGR', 'WTEFF_DGR', 'SIAFLR_STP', 'SIBFLR_STP', 'SIAFLR_SLD', 'SIBFLR_SLD', 'SIAFLR_ERC', 'SIBFLR_ERC', 'SIAFLR_ORM', 'SIBFLR_ORM', 'SIAFLR_SCS', 'SIBFLR_SCS', 'SIAFLR_CBS', 'SIBFLR_CBS', 'SIAFLR_STR', 'SIBFLR_STR', 'SIAFLR_HGD', 'SIBFLR_HGD', 'SIAFLR_CNS', 'SIBFLR_CNS', 'SIAFLR_HYP', 'SIAFLR_HER', 'SIBFLR_HER', 'SIAFLR_SMA', 'SIBFLR_SMA', 'SIAFLR_MDD', 'SIBFLR_MDD', 'SIAFLR_LAR', 'SIBFLR_LAR', 'KOFTR_CD']]
eight_codes #코드만 뽑ㄱㅣ

,CMBLC_ID,SBLT_ID,SMAR_NO,SLTP_CD,STQLT_CD,RHGLT_GGRP,WTHR_CD,TPGRP_TPCD,CLZN_CD,PRRCK_LARG,...,SIAFLR_HYP,SIAFLR_HER,SIBFLR_HER,SIAFLR_SMA,SIBFLR_SMA,SIAFLR_MDD,SIBFLR_MDD,SIAFLR_LAR,SIBFLR_LAR,KOFTR_CD
0,121.0,0.0,4.0,2.0,3.0,0.0,101001.0,5.0,1.0,3.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,11005.0
1,84.0,0.0,12.0,2.0,2.0,0.0,101004.0,3.0,1.0,2.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,12018.0
2,84.0,0.0,13.0,2.0,3.0,0.0,101004.0,1.0,1.0,2.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,12018.0
3,84.0,0.0,3.0,3.0,2.0,0.0,101001.0,3.0,1.0,2.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,11005.0
4,82.0,0.0,3.0,3.0,1.0,0.0,101001.0,3.0,1.0,2.0,...,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912327,0.0,0.0,40.0,1.0,3.0,1.0,101999.0,1.0,2.0,1.0,...,1.0,2.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,11017.0
912328,0.0,0.0,239.0,2.0,1.0,1.0,101001.0,5.0,2.0,2.0,...,2.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,0.0
912329,0.0,0.0,53.0,2.0,3.0,3.0,101001.0,3.0,2.0,1.0,...,3.0,2.0,3.0,2.0,2.0,2.0,2.0,4.0,2.0,11006.0
912330,116.0,0.0,1.0,1.0,2.0,1.0,101001.0,3.0,1.0,3.0,...,1.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,11005.0
912331,0.0,0.0,13.0,2.0,2.0,1.0,101001.0,5.0,2.0,1.0,...,1.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,11006.0

In [6]:

eight_reals.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/REALS_80.parquet', index=False)
eight_codes.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/CODES_80.parquet', index=False)

In [26]:
two_reals.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/REALS_20.parquet', index=False)
two_codes.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/CODES_20.parquet', index=False)

In [7]:
import category_encoders as ce
eight_codes = pd.read_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/CODES_80.parquet')
two_codes = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/CODES_20.parquet')

encoder = ce.BinaryEncoder(cols=eight_codes.columns) #바이너리 인코딩

eight_bin = encoder.fit_transform(eight_codes) #훈련용
two_bin = encoder.transform(two_codes) #테스트용

eight_df = pd.DataFrame()
two_df = pd.DataFrame()

eight_df = pd.concat([eight_df, eight_bin], axis=1)
two_df = pd.concat([two_df, two_bin], axis=1)
eight_df

,CMBLC_ID_0,CMBLC_ID_1,CMBLC_ID_2,CMBLC_ID_3,SBLT_ID_0,SMAR_NO_0,SMAR_NO_1,SMAR_NO_2,SMAR_NO_3,SMAR_NO_4,...,SIBFLR_MDD_0,SIBFLR_MDD_1,SIAFLR_LAR_0,SIAFLR_LAR_1,SIBFLR_LAR_0,SIBFLR_LAR_1,KOFTR_CD_0,KOFTR_CD_1,KOFTR_CD_2,KOFTR_CD_3
0,0,0,0,1,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
1,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,1,0
2,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,1,0
3,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
4,0,0,1,1,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912327,1,0,0,1,1,0,1,1,0,0,...,1,0,0,1,0,1,0,1,0,0
912328,1,0,0,1,1,0,1,1,1,1,...,1,0,0,1,0,1,0,0,1,1
912329,1,0,0,1,1,0,0,1,0,0,...,0,1,1,0,0,1,0,1,1,1
912330,1,0,1,0,1,0,0,0,0,1,...,0,1,0,1,0,1,0,0,0,1
912331,1,0,0,1,1,0,0,0,0,0,...,1,0,0,1,0,1,0,1,1,1

In [12]:
eight_df.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/binary/BIN_CODES_80.parquet', index=False)
two_df.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/binary/BIN_CODES_20.parquet')

In [28]:
new_df.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/binary/BIN_CODES_80.parquet',index=False)

In [84]:
eight_bin.to_csv('../LAST/binaryEncoding/EIGHTY_BINARY_CODES.csv', index=False)
two_bin.to_csv('../LAST/binaryEncoding/TWENTY_BINARY_CODES.csv', index=False)

In [3]:
eight_norm = pd.read_parquet('../LAST/normalization/EIGHTY_NORM_REALS.parquet')
two_norm = pd.read_parquet('../LAST/normalization/TWENTY_NORM_REALS.parquet')

two_norm

FileNotFoundError: [Errno 2] No such file or directory: '../LAST/normalization/EIGHTY_NORM_REALS.parquet'

In [13]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 훈련 데이터를 이용하여 MinMaxScaler를 초기화하고 훈련
scaler = MinMaxScaler()
train_data = pd.read_parquet("/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/REALS_80.parquet")  # 훈련 데이터 읽기
normalized_train_data = scaler.fit_transform(train_data)  # 훈련 데이터로 스케일러 훈련

# 테스트 데이터를 정규화
test_data = pd.read_parquet("/home/kng/kng/MOUNTAIN2/testDatas/REALS_20.parquet")  # 테스트 데이터 읽기
normalized_test_data = scaler.transform(test_data)  # 테스트 데이터 정규화

# 정규화된 테스트 데이터를 데이터프레임으로 변환
normalized_train_df = pd.DataFrame(normalized_train_data, columns=train_data.columns)
normalized_test_df = pd.DataFrame(normalized_test_data, columns=test_data.columns)

# 정규화된 테스트 데이터 출력
#print("Normalized test data:\n", normalized_test_df)

normalized_train_df.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/normalized/NORM_REALS_80.parquet',index=False)
normalized_test_df.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/normalized/NORM_REALS_20.parquet', index=False)

In [14]:
eight_norm = pd.read_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/normalized/NORM_REALS_80.parquet')
eight_code = pd.read_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/binary/BIN_CODES_80.parquet')

two_norm = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/normalized/NORM_REALS_20.parquet')
two_code = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/binary/BIN_CODES_20.parquet')

In [15]:
eight_land = pd.read_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/SMOTE_LANDSLIDE_80.parquet')
two_land = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/LANDSLIDE_20.parquet')

In [18]:
eight_conc = pd.concat([eight_norm, eight_code], axis=1)
two_conc = pd.concat([two_norm, two_code], axis=1)

,avg_temp,lowest_temp,highest_temp,rainfalling_hr_asos,1hr_rainfall_mm_asos,daily_rainfall_asos,max_windspeed_asos,avg_windspeed_asos,avg_dewpoint_temp,min_rhum_per,...,SIBFLR_MDD_0,SIBFLR_MDD_1,SIAFLR_LAR_0,SIAFLR_LAR_1,SIBFLR_LAR_0,SIBFLR_LAR_1,KOFTR_CD_0,KOFTR_CD_1,KOFTR_CD_2,KOFTR_CD_3
0,0.769968,0.788396,0.724868,0.0,0.000000,0.000000,0.111639,0.111111,0.846154,0.77,...,1,1,0,1,0,1,0,1,1,1
1,0.769968,0.788396,0.724868,0.0,0.000000,0.000000,0.111639,0.111111,0.846154,0.77,...,1,1,0,1,0,1,0,1,1,1
2,0.769968,0.788396,0.724868,0.0,0.000000,0.000000,0.111639,0.111111,0.846154,0.77,...,0,1,1,0,0,1,0,0,1,1
3,0.769968,0.788396,0.724868,0.0,0.000000,0.000000,0.111639,0.111111,0.846154,0.77,...,0,1,1,0,0,1,0,0,1,1
4,0.769968,0.788396,0.724868,0.0,0.000000,0.000000,0.111639,0.111111,0.846154,0.77,...,0,1,1,0,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120144,0.613419,0.535836,0.656085,0.0,0.046814,0.019173,0.087886,0.092593,0.637821,0.50,...,1,0,1,0,0,1,0,1,1,1
120145,0.613419,0.535836,0.656085,0.0,0.046814,0.019173,0.087886,0.092593,0.637821,0.50,...,1,0,1,0,0,1,0,1,1,1
120146,0.613419,0.535836,0.656085,0.0,0.046814,0.019173,0.087886,0.092593,0.637821,0.50,...,0,1,1,0,0,1,0,1,1,1
120147,0.613419,0.535836,0.656085,0.0,0.046814,0.019173,0.087886,0.092593,0.637821,0.50,...,0,1,1,0,0,1,0,0,1,1
120148,0.613419,0.535836,0.656085,0.0,0.046814,0.019173,0.087886,0.092593,0.637821,0.50,...,0,1,1,0,0,1,0,1,1,1

In [20]:
eight_final = pd.concat([eight_conc, eight_land], axis=1)
two_final = pd.concat([two_conc, two_land], axis=1)

In [21]:
eight_final.to_parquet('/home/kng/kng/MOUNTAIN2/trainDatas/SMOTE/final/SMOTED_FINAL_80.parquet',index=False)
two_final.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/final/SMOTED_FINAL_20.parquet',index=False)

In [28]:
import pandas as pd

# Parquet 파일 불러오기
test_data = pd.read_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/final/SMOTED_FINAL_20.parquet')

# is_landslides 열의 값이 1인 행 추출
landslides_data = test_data[test_data['is_landslided'] == 1]

# 1인 값의 개수
num_landslides = landslides_data.shape[0]

# is_landslides 열의 값이 0인 행 추출
non_landslides_data = test_data[test_data['is_landslided'] == 0]

# 1의 개수에 맞게 0인 행 삭제
if num_landslides < non_landslides_data.shape[0]:
    # 1의 개수에 맞게 0인 행을 삭제
    non_landslides_data = non_landslides_data.sample(n=num_landslides, random_state=42)

# 수정된 데이터프레임 생성
balanced_data = pd.concat([landslides_data, non_landslides_data], ignore_index=True)

# 새로운 Parquet 파일로 저장
balanced_data.to_parquet('/home/kng/kng/MOUNTAIN2/testDatas/SMOTE/final/balanced_data.parquet', index=False)